version: "3.7"

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:4200"
      #- 80:80
    volumes:
      - ./frontend/:/frontend/

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/go-app/
    ports:
      - "3000:3000"
    links:
      - database

  database:
    container_name: "database"
    image: mariadb:10.6.3
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: rest_api
      MARIADB_USER: rest_user
      MARIADB_PASSWORD: rest_password
    ports:
        - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql:rw"
      