FROM golang:1.16
#ENV GOPATH=/go-app
#ENV GOROOT=/go-app

RUN mkdir /build
ADD ./src /build/
WORKDIR /build
#RUN go mod download
 
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /build ./
CMD ["./app"]  